server:
  servlet:
    context-path: /user  # 服务自身前缀
spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 192.168.1.4:8848,192.168.1.4:8850,192.168.1.4:8852
      username: 'nacos'
      password: 'nacos'
      discovery:
        group: dms-practice
  #      config:
#        group: dms-practice
#        namespace: public
#        prefix: user-service
#        file-extension: yml
    loadbalancer:
      nacos:
        enabled: true
  config:
    import:
      - nacos:user-service.yml?group=dms-practice&namespace=public